# Generated by Django 3.2.8 on 2022-01-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(upload_to='image/thumbnail')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('length', models.IntegerField()),
                ('resource', models.FileField(upload_to='image/resource')),
            ],
        ),
    ]
