# Generated by Django 3.2.8 on 2022-01-30 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
