# Generated by Django 3.2.8 on 2022-01-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slugs',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
